---

- name: install epel
  yum: name=epel-release

- name: install RPM packages required for galaxy
  yum: name={{item}}
  with_items:
  - gcc
  - git
  - httpd
  - iptables-services
  - libjpeg
  - libselinux-python
  - libsemanage-python
  - make
  - memcached
  - mod_wsgi
  - mod_ssl
  - python-devel
  - python-pip
  - python-psycopg2
  - python-setuptools
  - PyYAML
  - python-memcached
  - rabbitmq-server
  - supervisor
  - tmux
  - libtiff-devel
  - libjpeg-devel
  - libzip-devel
  - freetype-devel
  - lcms2-devel
  - libwebp-devel
  - tcl-devel
  - tk-devel

- name: install development tool packages
  yum: name={{item}}
  with_items:
  - npm
  when: galaxy_install_dev_tools

- name: Install django
  pip: name=django version=1.8.3

- name: Install pip packages
  pip: name={{item}}
  with_items:
  - pexpect
  - decorator
  - django-allauth
  - django-autofixture
  - django-avatar
  - django-bootstrap-form
  - django-celery
  - django-filter
  - django-site-maintenance
  - djangorestframework==3.0.5
  - django-debug-toolbar
  - django-haystack
  - drf-haystack
  - elasticsearch==1.7.0   # Latest version not compatible with django-haystack
  - elasticsearch-dsl
  - markdown==2.4.1 # 2.5 currently has a python 2.6.x incompatibility
  - PyGithub
  - requests
  - requests-oauthlib
  - rst2html5-tools
  - requests
  - ansible-lint
  - gitpython

# the avatars directory needs to be there, otherwise the library
# will complain. It isn't used, as all the avatar info is stored
# in the database

- name: create galaxy_manage group
  group: name=galaxy_manage state=present

- name: configure django-avatars directory
  file: path=/var/www/avatars state=directory mode=0755 owner=apache group=galaxy_manage

- name: add vagrant to galaxy_manage group
  user: name=vagrant append=yes groups=galaxy_manage
  when: galaxy_env == "DEV"

#- name: add centos to galaxy_manage group
#  user: name=centos append=yes groups=galaxy_manage
#  when: galaxy_env == "PROD"

- name: add apache to galaxy_manage group
  user: name=apache append=yes groups=galaxy_manage
  when: galaxy_env == "PROD"

# semanage fcontext -a -t httpd_log_t "/var/log/galaxy(/.*)?"
# restorecon -R -v /var/log/galaxy

# the galaxy log directory will be handled by packaging in the future
- name: create galaxy log directory - production
  file:
      path: "{{ galaxy_log_dir }}"
      state: directory
      mode: 0770
      owner: root
      group: galaxy_manage
  when: galaxy_env == "PROD"

- name: create galaxy log directory - development
  file:
      path: "{{ galaxy_log_dir }}"
      state: directory
      mode: 0775
      owner: vagrant
      group: vagrant
  when: galaxy_env == "DEV"

- name: set galaxy log directory selinux permissions
  file:
      path: "{{ galaxy_log_dir }}"
      state: directory
      owner: root
      group: galaxy_manage
      recurse: yes
      seuser: system_u
      serole: object_r
      setype: httpd_log_t
  when: galaxy_env == "PROD" and galaxy_install_selinux

- name: set galaxy log directory default acl
  acl:
      name: "{{ galaxy_log_dir }}"
      default: yes
      etype: group
      entity: galaxy_manage
      permissions: rw
      state: present
  when: galaxy_env == "PROD"
